/*
트랜잭션 실습
*/

SELECT * FROM ACCOUNT; -- < 이렇게 SELECT 한 것도 트랜잭션 처리이다.

UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE - 10000
    WHERE  
        ACC_NO = '101-11-1001';
        
UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE + 10000
    WHERE  
        ACC_NO = '101-11-1003';

SELECT * FROM ACCOUNT;

-- 작업 확정
COMMIT;

-- 실습 8-2
UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE - 10000
    WHERE  
        ACC_NO = '101-11-1001';
        
UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE + 10000
    WHERE  
        ACC_NO = '101-11-1003';

SELECT * FROM ACCOUNT;

-- 작업 취소
ROLLBACK;

-- 실습 8-3
SHOW AUTOCOMMIT;

SET AUTOCOMMIT ON;

SET AUTOCOMMIT OFF;

UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE - 10000
    WHERE  
        ACC_NO = '101-11-1001';
        
UPDATE ACCOUNT SET
        ACC_BALANCE = ACC_BALANCE + 10000
    WHERE  
        ACC_NO = '101-11-1003';

SELECT * FROM ACCOUNT;
