//71P
select ename, initcap(ename) "INITCAP" 
FROM EMP
WHERE DEPTNO = 10;

SELECT NAME, INITCAP(NAME) "INITCAP"
FROM PROFESSOR WHERE DEPTNO = 101;

//72P
SELECT ENAME, LOWER(ENAME) "LOWER", UPPER(ENAME) "UPPER"
FROM EMP WHERE DEPTNO = 10;

//73P
SELECT ENAME, LENGTH(ENAME) "LENGTH" , LENGTHB(ENAME) "LENGTH"
FROM EMP WHERE DEPTNO = 20;

SELECT '서진수' "NAME", LENGTH('서진수') "LENGTH",
                        LENGTH('서진수') "LENGTHB"
FROM DUAL;

//74P
SELECT ENAME, LENGTH(ENAME)
FROM EMP WHERE LENGTH(ENAME)>LENGTH('&ENAME');
