//71P
select ename, initcap(ename) "INITCAP" 
FROM EMP
WHERE DEPTNO = 10;

SELECT NAME, INITCAP(NAME) "INITCAP"
FROM PROFESSOR WHERE DEPTNO = 101;

//72P
SELECT ENAME, LOWER(ENAME) "LOWER", UPPER(ENAME) "UPPER"
FROM EMP WHERE DEPTNO = 10;

//73P
SELECT ENAME, LENGTH(ENAME) "LENGTH" , LENGTHB(ENAME) "LENGTH"
FROM EMP WHERE DEPTNO = 20;

SELECT '서진수' "NAME", LENGTH('서진수') "LENGTH",
                        LENGTH('서진수') "LENGTHB"
FROM DUAL;

//74P
SELECT ENAME, LENGTH(ENAME)
FROM EMP WHERE LENGTH(ENAME)>LENGTH('&ENAME');

SELECT CONCAT(ENAME, JOB) FROM EMP WHERE DEPTNO=10;

COL "3,2" FOR A6
COL "-3,2" FOR A6
COL "-3,4" FOR A6

SELECT SUBSTR('ABCDE',3,2) "3,2",
        SUBSTR('ABCDE',-3,2) "-3,2",
        SUBSTR('ABCDE',-3,4) "-3,4"
        FROM DUAL;
        
        
SELECT NAME, SUBSTR(JUMIN,3,4) "BIRTHDAY",
            SUBSTR(JUMIN,3,4)-1 "BIRTHDAY -1"
            FROM STUDENT
            WHERE DEPTNO1 = 101;

SELECT '서진수' "NAME" , SUBSTR('서진수',1,2) "SUBSTR",
                        SUBSTRB('서진수',1,2) "SUBSTRB"
            FROM DUAL;
