SELECT * FROM EMP;

SELECT EMPNO, ENAME FROM EMP;

--32P
SELECT NAME, 'GOOD MORNING~~!' "GOOD MORNING" FROM PROFESSOR;

--33P
SELECT DNAME, ',IT''S DEPTNO : ', DEPTNO "DNAME AND DEPTNO" FROM DEPT;

--34P 
SELECT PROFNO , NAME, PAY FROM PROFESSOR;

SELECT PROFNO "PROF'S NO" , NAME AS "PROF'S NAME" , PAY PROF_PAY FROM PROFESSOR;

--35P
SELECT DEPTNO FROM EMP ;
SELECT DISTINCT DEPTNO FROM EMP;

--36
SELECT JOB, ENAME FROM EMP ORDER BY 1,2;
SELECT DISTINCT JOB, ENAME FROM EMP ORDER BY 1,2;

SELECT JOB, DISTINCT ENAM FROM EMP ORDER BY 1,2; // 오류 표현식

//38P
SELECT ENAME||'-'||JOB FROM EMP;

SELECT ENAME ||' ''S JOB IS ' || JOB "NAME AND JOB" FROM EMP;

// 39P 연습문제 1
SELECT NAME ||'''S ID : '|| ID||', WEIGHT IS '|| WEIGHT ||'Kg' FROM STUDENT;

// 연습문제 2
SELECT ENAME || '(' || JOB || '), '||ENAME ||''''||JOB||'''' FROM EMP;

// 연습문제 3
SELECT ENAME || '''S SAL IS $'|| SAL FROM EMP;

//41P
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO=7900;
SELECT ENAME, SAL FROM EMP WHERE SAL<900;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME=SMITH; //오류 예시
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME = 'SMITH' ;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME= 'smith'; //문자 조회시, 작은따옴표와 대소문자 구분 확인

//42P
select ename, hiredate from emp where ename = 'SMITH';
SELECT ENAME, HIREDATE FROM EMP WHERE ENAME = 'SMITH' ;

SELECT EMPNO, ENAME , SAL FROM EMP WHERE HIREDATE = '80/12/17';

//44P
SELECT ENAME, SAL FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL ,SAL+100 FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL, SAL*1.1 FROM EMP WHERE DEPTNO = 10;

//45P
SELECT EMPNO, ENAME , SAL FROM EMP WHERE SAL >= 4000;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME >= 'W';

//46P
SELECT ENAME , HIREDATE FROM EMP;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE >= '81/12/25';

//47P
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL BETWEEN 2000 AND 3000;

//48P
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL >= 2000
AND SAL <=3000;

SELECT ENAME FROM EMP ORDER BY ENAME;

SELECT ENAME FROM EMP
WHERE ENAME BETWEEN 'JAMES' AND 'MARTIN' ORDER BY ENAME;

//49P
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (10,20);

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL LIKE '1%' ;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE ENAME LIKE 'A%' ;

//50P
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE HIREDATE LIKE '80%';

SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE HIREDATE LIKE %80;

SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE HIREDATE LIKE '___12%';

//52P 
SELECT EMPNO, ENAME, COMM FROM EMP WHERE DEPTNO IN (20,30);

//53
SELECT EMPNO, ENAME, COMM FROM EMP WHERE COMM IS NULL;
SELECT EMPNO, ENAME, COMM FROM EMP WHERE COMM IS NOT NULL;

//54
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE HIREDATE > '82-01-01' AND SAL >= 1300;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE > '82-01-01' OR SAL >= 1300;

SELECT EMPNO, ENAME, SAL, COMM FROM EMP WHERE SAL > 1000 AND (COMM < 1000 OR COMM IS NULL) ;
SELECT EMPNO, ENAME, SAL, COMM FROM EMP WHERE SAL > 1000 AND COMM < 1000 OR COMM IS NULL;
-- AND는 곱하기, OR은 더하기로 통하기 때문에 OR 먼저 계산하고 싶으면 괄호를 쳐준다.

//55P
SELECT EMPNO, ENAME, SAL FROM EMP WHERE EMPNO = &EMPNO; //7092
SET VERIFY OFF 
SELECT EMPNO, ENAME, SAL FROM EMP WHERE EMPNO = &EMPNO;

//57P
SELECT ENAME, SAL, HIREDATE FROM EMP;
SELECT ENAME, SAL, HIREDATE FROM EMP ORDER BY ENAME;

//58P 
SELECT DEPTNO, SAL, ENAME FROM EMP ORDER BY DEPTNO ASC, SAL DESC;
SELECT ENAME, SAL, HIREDATE FROM EMP WHERE SAL > 1000 ORDER BY 2, 1;

//60P
SELECT STUDNO, NAME, DEPTNO1 , 1
FROM STUDENT WHERE DEPTNO1 = 101
UNION ALL
SELECT PROFNO, NAME, DEPTNO, 2
FROM PROFESSOR WHERE DEPTNO = 101;

//61P
SELECT STUDNO, NAME, DEPTNO1, 1
FROM STUDENT WHERE DEPTNO1 = 101
UNION
SELECT PROFNO, NAME, DEPTNO, 2
FROM PROFESSOR WHERE DEPTNO = 101;

SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO1 = 101
UNION
SELECT STUDNO, NAME 
FROM STUDENT WHERE DEPTNO2 = 201;

SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO1 = 101
UNION ALL
SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO2 = 201;

SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO1 = 101
UNION ALL
SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO2 = 201;

//63P
SELECT STUDNO, NAME 
FROM STUDENT WHERE DEPTNO1 = 101
INTERSECT
SELECT STUDNO, NAME
FROM STUDENT WHERE DEPTNO2 = 201;

SELECT EMPNO, ENAME , SAL
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL
FROM EMP WHERE SAL > 2500;

//64P
SELECT STUDNO, NAME
FROM STUDENT
UNION
SELECT PROFNO FROM PROFESSOR; // SELECT 절의 컬럼 개수가 다를 경우의 오류 예시

SELECT STUDNO, NAME
FROM STUDENT
UNION
SELECT NAME, PROFNO FROM PROFESSOR; // 오류 예시