SELECT * FROM EMP;

SELECT EMPNO, ENAME FROM EMP;

--32P
SELECT NAME, 'GOOD MORNING~~!' "GOOD MORNING" FROM PROFESSOR;

--33P
SELECT DNAME, ',IT''S DEPTNO : ', DEPTNO "DNAME AND DEPTNO" FROM DEPT;

--34P 
SELECT PROFNO , NAME, PAY FROM PROFESSOR;

SELECT PROFNO "PROF'S NO" , NAME AS "PROF'S NAME" , PAY PROF_PAY FROM PROFESSOR;

--35P
SELECT DEPTNO FROM EMP ;
SELECT DISTINCT DEPTNO FROM EMP;

--36
SELECT JOB, ENAME FROM EMP ORDER BY 1,2;
SELECT DISTINCT JOB, ENAME FROM EMP ORDER BY 1,2;

SELECT JOB, DISTINCT ENAM FROM EMP ORDER BY 1,2; // 오류 표현식

//38P
SELECT ENAME||'-'||JOB FROM EMP;

SELECT ENAME ||' ''S JOB IS ' || JOB "NAME AND JOB" FROM EMP;

// 39P 연습문제 1
SELECT NAME ||'''S ID : '|| ID||', WEIGHT IS '|| WEIGHT ||'Kg' FROM STUDENT;

// 연습문제 2
SELECT ENAME || '(' || JOB || '), '||ENAME ||''''||JOB||'''' FROM EMP;

// 연습문제 3
SELECT ENAME || '''S SAL IS $'|| SAL FROM EMP;

//41P
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO=7900;
SELECT ENAME, SAL FROM EMP WHERE SAL<900;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME=SMITH; //오류 예시
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME = 'SMITH' ;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME= 'smith'; //문자 조회시, 작은따옴표와 대소문자 구분 확인

//42P
select ename, hiredate from emp where ename = 'SMITH';
SELECT ENAME, HIREDATE FROM EMP WHERE ENAME = 'SMITH' ;

SELECT EMPNO, ENAME , SAL FROM EMP WHERE HIREDATE = '80/12/17';

//44P
SELECT ENAME, SAL FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL ,SAL+100 FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL, SAL*1.1 FROM EMP WHERE DEPTNO = 10;

//45P
SELECT EMPNO, ENAME , SAL FROM EMP WHERE SAL >= 4000;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME >= 'W';

//46P
SELECT ENAME , HIREDATE FROM EMP;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE >= '81/12/25';

//47P
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL BETWEEN 2000 AND 3000;

//
